# Generated by Django 3.2.5 on 2021-07-13 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SymbolDailyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('rsi', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('volume', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('open', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('close', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('sma10', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('telegram_id', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('expired_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('login_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
