# Generated by Django 3.2.5 on 2021-07-13 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.investor')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.symbol')),
            ],
        ),
    ]
