# Generated by Django 3.2.5 on 2021-07-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_stockasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='exchange',
            field=models.CharField(default='VIETNAM', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symbol',
            name='screener',
            field=models.CharField(default='VIETNAM', max_length=200),
            preserve_default=False,
        ),
    ]
